-- This file is auto-generated by scripts/gen_completion.lua.
return {
  actions = {
    attach = {
      flags = {
        bufnr = true,
        force = false,
        trigger = true,
      },
    },
    blame = {
      flags = {
        ignore_whitespace = false,
      },
    },
    blame_line = {
      flags = {
        full = false,
        ignore_whitespace = false,
      },
    },
    change_base = {
      flags = {
        global = false,
      },
      positional = {
        {
          name = 'base',
          revision = true,
          values = { 'FILE' },
        },
        {
          boolean = true,
          name = 'global',
          required = true,
        },
      },
    },
    diffthis = {
      flags = {
        split = { 'aboveleft', 'belowright', 'topleft', 'botright' },
        vertical = false,
      },
      positional = {
        {
          name = 'base',
          required = true,
          revision = true,
          values = { 'FILE' },
        },
      },
    },
    nav_hunk = {
      flags = {
        count = true,
        foldopen = false,
        greedy = false,
        navigation_message = false,
        preview = false,
        target = { 'unstaged', 'staged', 'all' },
        wrap = false,
      },
      positional = {
        {
          name = 'direction',
          required = true,
          values = { 'first', 'last', 'next', 'prev' },
        },
      },
    },
    next_hunk = {
      flags = {
        count = true,
        foldopen = false,
        greedy = false,
        navigation_message = false,
        preview = false,
        target = { 'unstaged', 'staged', 'all' },
        wrap = false,
      },
    },
    prev_hunk = {
      flags = {
        count = true,
        foldopen = false,
        greedy = false,
        navigation_message = false,
        preview = false,
        target = { 'unstaged', 'staged', 'all' },
        wrap = false,
      },
    },
    reset_base = {
      flags = {
        global = false,
      },
      positional = {
        {
          boolean = true,
          name = 'global',
          required = true,
        },
      },
    },
    setloclist = {
      positional = {
        {
          name = 'nr',
          values = { '0' },
        },
        {
          name = 'target',
          required = true,
          values = { 'attached', 'all' },
        },
      },
    },
    setqflist = {
      flags = {
        nr = true,
        open = false,
        use_location_list = false,
      },
      positional = {
        {
          name = 'target',
          required = true,
          values = { '0', 'attached', 'all' },
        },
      },
    },
    show = {
      positional = {
        {
          name = 'revision',
          required = true,
          revision = true,
          values = { 'FILE' },
        },
      },
    },
    show_commit = {
      positional = {
        {
          name = 'revision',
          revision = true,
        },
        {
          name = 'open',
          required = true,
          values = { 'vsplit', 'tabnew' },
        },
      },
    },
    toggle_current_line_blame = {
      positional = { {
        boolean = true,
        name = 'value',
      } },
    },
    toggle_deleted = {
      positional = { {
        boolean = true,
        name = 'value',
      } },
    },
    toggle_linehl = {
      positional = { {
        boolean = true,
        name = 'value',
      } },
    },
    toggle_numhl = {
      positional = { {
        boolean = true,
        name = 'value',
      } },
    },
    toggle_signs = {
      positional = { {
        boolean = true,
        name = 'value',
      } },
    },
    toggle_word_diff = {
      positional = { {
        boolean = true,
        name = 'value',
      } },
    },
  },
}
